# Generated by Django 5.2.1 on 2025-05-21 16:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entreprise',
            options={'ordering': ['nom_entreprise'], 'verbose_name': 'Profil Entreprise', 'verbose_name_plural': 'Profils Entreprise'},
        ),
        migrations.AlterModelOptions(
            name='freelance',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Profil Freelance', 'verbose_name_plural': 'Profils Freelance'},
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_entreprise',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_freelance',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entreprise',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Numéro SIRET'),
        ),
        migrations.AddField(
            model_name='freelance',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelance',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(blank=True, choices=[('FR', 'Freelance'), ('EN', 'Entreprise')], max_length=2, null=True, verbose_name="Type d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='description',
            field=models.TextField(blank=True, help_text='Présentation de votre entreprise', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='email_contact',
            field=models.EmailField(max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom_entreprise',
            field=models.CharField(max_length=255, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='site_web',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'type_utilisateur': 'EN'}, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='bio',
            field=models.TextField(blank=True, help_text='Décrivez votre parcours et expérience', verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='competences',
            field=models.TextField(help_text='Liste de compétences séparées par des virgules', verbose_name='Compétences'),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='lien_portfolio',
            field=models.URLField(blank=True, help_text='URL de votre portfolio en ligne', verbose_name='Lien vers le portfolio'),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='tarif_horaire',
            field=models.DecimalField(decimal_places=2, help_text='Tarif horaire moyen pour vos prestations', max_digits=8, verbose_name='Tarif horaire (€)'),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'type_utilisateur': 'FR'}, on_delete=django.db.models.deletion.CASCADE, related_name='freelance_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name="Nom d'utilisateur"),
        ),
    ]
