# Generated by Django 5.2.1 on 2025-05-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateField()),
                ('est_active', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='users.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='users.freelance')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='missions.mission')),
            ],
            options={
                'unique_together': {('mission', 'freelance')},
            },
        ),
    ]
