# Generated by Django 5.2.1 on 2025-05-21 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidature',
            options={'ordering': ['-date_postulation'], 'verbose_name': 'Candidature', 'verbose_name_plural': 'Candidatures'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='mission',
            name='competences_requises',
            field=models.TextField(blank=True, help_text='Listez les compétences nécessaires séparées par des virgules', verbose_name='Compétences requises'),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='date_postulation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='freelance',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'FR'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Freelance candidat'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='message',
            field=models.TextField(verbose_name='Message de motivation'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='missions.mission', verbose_name='Mission concernée'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut de la candidature'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget alloué (€)'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_limite',
            field=models.DateField(verbose_name='Date limite de candidature'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='entreprise',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'EN'}, on_delete=django.db.models.deletion.CASCADE, related_name='missions_publiees', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise recruteuse'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='est_active',
            field=models.BooleanField(default=True, verbose_name='Mission active'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre de la mission'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['-date_postulation'], name='missions_ca_date_po_53abc7_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['statut'], name='missions_ca_statut_5988bf_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['-date_creation'], name='missions_mi_date_cr_3e7dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['entreprise'], name='missions_mi_entrepr_0d2efb_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['est_active'], name='missions_mi_est_act_b68883_idx'),
        ),
    ]
