"""
Django settings for Entreprise_Freelance project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ww%24%iwq0+qa))*yv(ukkb_k*r*8u$#7xfo#dehs%6xlt95!h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'missions.apps.MissionsConfig',
    'messagerie.apps.MessagerieConfig',
]

AUTH_USER_MODEL = 'users.Utilisateur'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Entreprise_Freelance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Chemin absolu vers votre dossier templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'messagerie.context_processors.unread_messages',
            ],
        },
    },
]
print("Template DIR:", os.path.join(BASE_DIR, 'templates'))

WSGI_APPLICATION = 'Entreprise_Freelance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import shutil

db_path = BASE_DIR / 'db.sqlite3'

# Workaround for Windows Controlled Folder Access (Ransomware Protection) blocking SQLite writes in Documents/OneDrive
if os.name == 'nt' and DEBUG:
    local_appdata = os.environ.get('LOCALAPPDATA')
    if local_appdata:
        writable_dir = Path(local_appdata) / 'EntrepriseFreelance'
        try:
            writable_dir.mkdir(parents=True, exist_ok=True)
            target_db = writable_dir / 'db.sqlite3'
            
            # If the database doesn't exist in AppData yet, copy the current one from BASE_DIR
            if not target_db.exists() and db_path.exists():
                shutil.copy2(db_path, target_db)
                
            db_path = target_db
        except Exception as e:
            print(f"Warning: Could not configure writable SQLite database in AppData ({e}). Using default path.")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': db_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'users:login'

